version: '3.1'

services:
  mysql:  
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  app:
    build: .
    container_name: app
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

  client:
    build: './client'
    network_mode: host
    container_name: client
    hostname: client
    restart: unless-stopped
    volumes:
      - ./client/app:/app
    ports:
      - "8080:8080"

  behat:
    image: docksal/behat
    network_mode: host
    container_name: behat
    hostname: behat
    volumes:
      - ./src:/src

  cypress:
    image: cypress/included:3.2.0
    network_mode: host
    container_name: cypress
    hostname: cypress
    working_dir: /e2e
    volumes:
      - ./src/tests/e2e:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix


secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt

volumes:
  mysql-data:
